### ISSUE TITLE
Significance stars and standardized paths not working

### ISSUE THREAD

**Issue by jorgesinval** [alishinski/lavaanPlot#11]
Hello!

I think that the `sig` and `stand` command aren't working.

Version 0.5.1

**Comment by alishinski** [comment]
These are working for me, to get significance stars you have to do `stars = "regress"` or `stars = "latent"` or `stars = "covs"` (or some combination thereof), `sig` lets you change the significance level. But if you have a reproducible example where these aren't working for you I'll check it out.

**Comment by jorgesinval** [comment]
You are right, although in the vignettes code you have `stars = TRUE`:

`lavaanPlot(model = fit, labels = labels, node_options = list(shape = "box", fontname = "Helvetica"), edge_options = list(color = "grey"), coefs = TRUE, covs = TRUE, stars = TRUE)
`

**Comment by Deleetdk** [comment]
I get no stars with either `stars = "regress"` or `stars = T`. I'm using the Github package version.
