### ISSUE TITLE
Print plots in PDFs

### ISSUE THREAD

**Issue by jorgesinval** [alishinski/lavaanPlot#12]
Is it possible to knit the diagrams on a PDF?

**Comment by alishinski** [comment]
This seems to be significantly trickier than it ought to be, but I'm looking into it.

**Comment by jorgesinval** [comment]
Excellent!

**Comment by Deleetdk** [comment]
I am just in general unable to save figures except for manually click Export in RStudio. The documentation does not seem to have anything on this. How does one save figures programmatically?

**Comment by mattansb** [comment]
I've come across the same problem. Has anyone been able to programmatically save the plots?

**Comment by mattansb** [comment]
Seems like this is solved by adding `always_allow_html: yes` in the `yaml` header!

**Comment by dongyiyi** [comment]
Yes, I met the same problem. How to save the plot to a pdf file?

**Comment by tafakkur** [comment]
Have you guys tried to embed your code in an .Rmd file and then knit it to HTML?
I've been doing that and can easily get plots in a PDF format

**Comment by tafakkur** [comment]
One possible workaround. 
```
tempDir <- tempfile()
dir.create(tempDir)
htmlFile <- file.path(tempDir, "lavaan_model.html")
htmltools::save_html(lavaan_model,htmlFile)

# webshot supports other formats as well (png, bmp etc.)
# This will create lavaan_model.pdf in the working directory

webshot::webshot(htmlFile,"lavaan_model.pdf") 
```

**Comment by jorgesinval** [comment]
Yes, and you can also use `pagedown::chrome_print()`. But if you only want to directly plot a diagram it is not straightforward.

**Comment by tafakkur** [comment]
That's true. Probably in the meantime, we could have a function that does all this work in the background. But we'll still only get screenshots and not diagrams.

**Comment by alishinski** [comment]
I wrote 2 new functions and put them in a new branch called [export_functions](https://github.com/alishinski/lavaanPlot/tree/export_plots):

 `save_png` will save your plot as a .png programmatically
`embed_plot_pdf` you can use in an .Rmarkdown document that you knit into a pdf to embed your plot

Give those a try and let me know what you think

**Comment by alishinski** [comment]
And whether they work, of course

**Comment by jorgesinval** [comment]
I just tried it, and it does not work:

`lavaanPlot::save_png(plot = fit,path = "test.svg")`

an error was created:


`Error: $ operator not defined for this S4 class`

**Comment by jorgesinval** [comment]
So... we always need to create a separate pdf (with only the plot) to then be added to the Rmarkdown one, right?

**Comment by alishinski** [comment]
Yeah the `embed_plot_pdf` function converts and saves the plot as a pdf (So you should use a .pdf file name) in your working directory and then uses `knitr::include_graphics` to put the plot into the knitted (knitr-ed?) .pdf. I haven't figured out how to do it without saving, but please let me know if you have any suggestions.

**Comment by shangeconnew** [comment]
I wonder where the '[export_functions](https://github.com/alishinski/lavaanPlot/tree/export_plots)' is now, you know, the link does not work. @alishinski
