### ISSUE TITLE
Digits

### ISSUE THREAD

**Issue by jorgesinval** [alishinski/lavaanPlot#13]
The option `digits =` should be added. If a parameter has a value of 0.90, it will appear as `0.9`.

**Comment by alishinski** [comment]
I think you're right, I'll work on this.

**Comment by jorgesinval** [comment]
Thank you, I hope you can keep improving this wonderful package!

**Comment by alishinski** [comment]
Thanks, I'm gonna try!

**Comment by alishinski** [comment]
Added digits option in this commit https://github.com/alishinski/lavaanPlot/commit/1e1066b0b3870e891f646e11b97e09e0c27f64e0

**Comment by jorgesinval** [comment]
Excellent, Alex. Is good to have you back!
