### ISSUE TITLE
cov coefs always plotted

### ISSUE THREAD

**Issue by mattansb** [alishinski/lavaanPlot#18]
The values of the covariances are always plotted, even when `coefs = FALSE` - is there a way to suppress this?
``` r
library(lavaan)
#> Warning: package 'lavaan' was built under R version 3.6.1
#> This is lavaan 0.6-4
#> lavaan is BETA software! Please report any bugs.
library(lavaanPlot)

model <- '
# measurement model
ind60 =~ x1 + x2 + x3
dem60 =~ y1 + y2 + y3 + y4
dem65 =~ y5 + y6 + y7 + y8
# regressions
dem65 ~~ ind60 + dem60
'

fit <- sem(model, data=PoliticalDemocracy)
lavaanPlot(model = fit, covs = TRUE, coefs = FALSE)
```
![image](https://user-images.githubusercontent.com/35330040/63342087-4cd15580-c353-11e9-9d5e-e832a41d42fa.png)

**Comment by mattansb** [comment]
Also, only cov between latent variables is plotted - can this be changed?

**Comment by willynilly** [comment]
Yes, I really need the covs plotted for observed variables.

**Comment by alishinski** [comment]
Fixed the original issue. Now coefs plot all or none with coefs = TRUE including covariances.
