### ISSUE TITLE
Add edge attributes for starred and unstarred edges

### ISSUE THREAD

**Issue by willynilly** [alishinski/lavaanPlot#19]
Add two parameters that allow me to specify the different edge attributes for the starred and unstarred edges.   These would be like "unstarred_edge_options" and "starred_edge_options".

With this feature, I will be able to more easily visually distinguish between starred and unstarred edges (maybe the starred edges are colored differently than the unstarred edges).

**Comment by alishinski** [comment]
This would be quite complicated to implement in the general case. What I can recommend is that you can get your lavaanPlot object as close as you can and save it, then you can get the grViz specification out of that object, tinker with it manually, then run it through the grViz function like this:

```
plot <- lavaanPlot(model = fit)
plot$x$diagram

str <- tinkered with version of plot$x$diagram

grViz(str)
```
