### ISSUE TITLE
Covariances for observed variances

### ISSUE THREAD

**Issue by tdienlin** [alishinski/lavaanPlot#24]
Hi Alex! Such a great package, thanks for sharing! It seems that it's not possible to display covariances of observed exogenous variables. See following example: 

```
library(lavaan); library(lavaanPlot)
model <- "
  wt ~~ disp
  mpg ~ cyl + disp + hp
  qsec ~ disp + hp + wt
"
fit <- sem(model, data = mtcars)
lavaanPlot(model = fit, coefs = TRUE, stand = TRUE, covs = TRUE)
````

![image](https://user-images.githubusercontent.com/29224415/84918559-09ee2480-b0c1-11ea-849c-c4daf7281ed9.png)

So the covariance between wt and disp is not displayed. Prob. only works for latent variables? Is it possible to include covariances for observed vars as well? That'd be great!

**Comment by gsborgeest** [comment]
@alishinski do you have any updates on this?

**Comment by alishinski** [comment]
The way it works is that it includes all of the covariance relationships that show up in the ParTable of the model object, which isn't necessarily just the ones you specify in the model syntax. I ran your code and I got a different version of the plot. Also, including that covariance makes lavaan throw an angry warning:

`In lavaan::lavaan(model = model, data = mtcars, model.type = "sem",  :
  lavaan WARNING: syntax contains parameters involving exogenous covariates; switching to fixed.x = FALSE`

![image](https://user-images.githubusercontent.com/6395934/101272698-8ef6f400-375c-11eb-95c1-f1bc2d4fe5e7.png)

And your version does have a covariance term reflected in the diagram, the one for mpg and qsec, which makes sense with those being the 2 DVs in your model. Mine has that one, the one you wanted, but also one for hp and cyl, which I don't understand why that's there.

So honestly I'm a little bit confused why I'm getting the results that I'm getting, but why we're getting different ones also. Were you using the CRAN version to get your version, or the github one?

**Comment by tdienlin** [comment]
That's weird. I'm getting the exact same figure as before, either when installing from github or from cran, using this code:

```
# devtools::install_git(url = "https://github.com/alishinski/lavaanPlot")
# install.packages("lavaanPlot")
library(lavaan); library(lavaanPlot)
model <- "
  wt ~~ disp
  mpg ~ cyl + disp + hp
  qsec ~ disp + hp + wt
"
fit <- sem(model, data = mtcars, fixed.x = FALSE)
lavaanPlot(model = fit, coefs = TRUE, stand = TRUE, covs = TRUE)
```


Here's my session info:

```
version 4.0.3 (2020-10-10)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Big Sur 10.16

Matrix products: default
LAPACK: /Library/Frameworks/R.framework/Versions/4.0/Resources/lib/libRlapack.dylib

locale:
[1] de_AT.UTF-8/de_AT.UTF-8/de_AT.UTF-8/C/de_AT.UTF-8/de_AT.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] lavaanPlot_0.5.2 lavaan_0.6-7    

loaded via a namespace (and not attached):
 [1] git2r_0.27.1       compiler_4.0.3     RColorBrewer_1.1-2 remotes_2.2.0      prettyunits_1.1.1 
 [6] tools_4.0.3        testthat_3.0.0     digest_0.6.27      pkgbuild_1.1.0     pkgload_1.1.0     
[11] jsonlite_1.7.1     memoise_1.1.0      rlang_0.4.9        cli_2.2.0          rstudioapi_0.13   
[16] yaml_2.2.1         pbivnorm_0.6.0     DiagrammeR_1.0.6.1 withr_2.3.0        stringr_1.4.0     
[21] fs_1.5.0           desc_1.2.0         htmlwidgets_1.5.2  devtools_2.3.2     rprojroot_2.0.2   
[26] stats4_4.0.3       glue_1.4.2         R6_2.5.0           processx_3.4.5     fansi_0.4.1       
[31] sessioninfo_1.1.1  callr_3.5.1        magrittr_2.0.1     usethis_1.6.3      ps_1.5.0          
[36] htmltools_0.5.0    ellipsis_0.3.1     MASS_7.3-53        assertthat_0.2.1   mnormt_2.0.2      
[41] stringi_1.5.3      visNetwork_2.0.9   tmvnsim_1.0-2      crayon_1.3.4
```

**Comment by Zweckoptimismus** [comment]
Hey all, 

first of all: thanks for the wonderful package, it's so handy to have these plots created automatically!

Second: I experienced the same issue as Tobias when using the lavaanPlot version 0.5.1 from CRAN. After updating to 0.5.2 via GitHub (using Tobias' code), covariances for observed exogeneous variables were successfully displayed. 
So I cross-checked and un-installed lavaanPlot, and reinstalled it from CRAN: again, no covariances. 
Back to the GitHub version: covariances. 

I have no idea how complex the process of pushing a new version from GitHub to CRAN is, but maybe this could fix the problem. :-) 

Otherwise: Tobias, good luck!

**Comment by tdienlin** [comment]
Can confirm, now it also works on my side (haven't changed anything in the code though). Never mind, great it's now working. Thank you!
