### ISSUE TITLE
Hide arrows for insignificant paths (not only the coefficient)

### ISSUE THREAD

**Issue by Buedenbender** [alishinski/lavaanPlot#27]
Is it possible to hide the arrows of non-significant paths?
Not only the path coefficients? I know that one can specify significance level (e.g. `sig = .05`) and 
consequently the non-significant coefficients (path-weights) are omitted, however it would
really improve readability for bigger models if it would be possible to also omit the
arrow.

**Minimal Reproducibel Example**

```
#Github MRE for hiding insignificant paths
library(lavaanPlot)

model <- 'mpg ~ cyl + disp + hp
          qsec ~ disp + hp + wt'

fit <- sem(model, data = mtcars)
summary(fit)

lavaanPlot(model = fit, 
           node_options = list(shape = "box", fontname = "Helvetica"), 
           edge_options = list(color = "grey"), 
           coefs = TRUE,
           stand = TRUE,
           # covs = TRUE,
           sig = .05,
           stars = "regress")
```

**Comment by alishinski** [comment]
It's not possible right now, but it could definitely be added, I'll put it on the to do list. In the meantime, if you need to modify a lavaanPlot diagram to omit some plots, you can always manually modify the diagram specification and get rid of paths you don't want. E.g.:

```
model <- " wt ~~ disp
  mpg ~ cyl + disp + hp
  qsec ~ disp + hp + wt"

fit <- sem(model, data = mtcars)
plo <- lavaanPlot(model = fit, coefs = TRUE, stand = TRUE, covs = TRUE)

# gives you the diagram specification
plo$x$diagram

# modify that and put into this function
grViz()
```

**Comment by CharlyMarie** [comment]
Hi there,

Has this feature been implemented? I have tried to play with both lavaanPlot and DiagrammeR to change the graph, but I am a bit too clumsy to do this manually.

**Comment by patc3** [comment]
Same here, this shows as completed in Jan 2022 but I don't see how to do it in the library.
