### ISSUE TITLE
argument to hide manifest variables

### ISSUE THREAD

**Issue by ogansser** [alishinski/lavaanPlot#31]
Hi, I am trying to hide the manifest variables, so that I can plot only the latent variables. Which argument do I need?

Olli

**Comment by alishinski** [comment]
It's not possible right now, so there is no argument, but it could definitely be added, I'll put it on the to do list. In the meantime, if you need to modify a lavaanPlot diagram to omit some paths, you can always manually modify the diagram specification and get rid of paths you don't want. E.g.:
```
model <- " wt ~~ disp
  mpg ~ cyl + disp + hp
  qsec ~ disp + hp + wt"

fit <- sem(model, data = mtcars)
plo <- lavaanPlot(model = fit, coefs = TRUE, stand = TRUE, covs = TRUE)

# gives you the diagram specification
plo$x$diagram

# modify that and put into this function
grViz()
```
