### ISSUE TITLE
How to position nodes

### ISSUE THREAD

**Issue by lordhagen94** [alishinski/lavaanPlot#32]
I created a plot for my serial mediation model using lavaanPlot and everything works fine except one thing. I can't find a way to reposition the nodes.

It currently looks like this:
![plot](https://user-images.githubusercontent.com/87430370/125930523-38956b59-95cc-4840-b58a-8defc67d6495.png)

And I want it to look like this (social comparison and fomo on top, subjective well-being and sns addiction in the bottom. for age and gender i have yet to find a good position):
![y9cyG](https://user-images.githubusercontent.com/87430370/125931022-0c5aba48-9475-4f3f-9419-f12e620df2a3.jpg)

If there is any way to do this please let me know!

**Comment by alishinski** [comment]
Unfortunately there's not really a way to do this within diagrammeRs layout system. The automatic layout is the sort of double edged sword, where it will give you something that looks reasonable with no effort on your part, but there's no full customization.
