### ISSUE TITLE
Improve argument order in the `lavaanPlot()`and `buildCall()` functions

### ISSUE THREAD

**Issue by mccarthy-m-g** [alishinski/lavaanPlot#34]
Currently the `lavaanPlot()` function has its arguments ordered like this:

```
lavaanPlot(name = "plot", model, labels = NULL, ...)
```

A huge improvement would be to order the arguments like this instead:

```
lavaanPlot(model, name = "plot", labels = NULL, ...)
```

The same change in argument order could also be made for the `buildCall()` function.

Having the model argument first is what most R users expect, since every function that takes a model object as input makes it its first argument. It would be great as an end-user if the lavaanPlot package followed this convention.

I'd be happy to file a PR if you're open to making this change!

**Comment by alishinski** [comment]
That is a good idea. I know there was a reason I didn't do it that way to begin with, but I can't remember what that is anymore, and I don't think it was a good reason. I made that change in the most recent commits.
