### ISSUE TITLE
Plot latent variables on the left-hand side, observed variable on the right.

### ISSUE THREAD

**Issue by igavronski** [alishinski/lavaanPlot#36]
Hi there,
I would like to plot a CFA with the latent variables on the left, instead of on the top.
For example:
```
HS.model <- ' visual  =~ x1 + x2 + x3      
textual =~ x4 + x5 + x6
speed   =~ x7 + x8 + x9 
'

fit <- cfa(HS.model, data=HolzingerSwineford1939)

lavaanPlot(model = fit, edge_options = list(color = "grey"))
```

Plots:
![Rplot](https://user-images.githubusercontent.com/14096908/155799025-f07f0c30-6218-4915-a2a9-946397f7cfb4.png)

And I would like to have:

![Rplot2](https://user-images.githubusercontent.com/14096908/155800384-a260f093-94b3-4ea1-9d53-a8fccdd19a30.png)

What needs to change in the lavaanPlot call to achieve the above plot?

Thanks in advance,

Iuri.

**Comment by igavronski** [comment]
Found myself:
```
lavaanPlot(model = fit, graph_options=list(rankdir="LR"), edge_options = list(color = "grey"))
```

Got from the documentation in: https://www.graphviz.org/doc/info/shapes.html


@alishinski , could you please update/upgrade the documentation with such an example?

**Comment by alishinski** [comment]
This is a good idea, thanks for the suggestion!

**Comment by alishinski** [comment]
Updated the intro to lavaanPlot vignette with some orientation and layout examples in: https://github.com/alishinski/lavaanPlot/commit/018d2a06235a573c93ca2e3b07a8ef35d50583ad

**Comment by igavronski** [comment]
Your examples are great!
Thanks!
