### ISSUE TITLE
CRAN release

### ISSUE THREAD

**Issue by M-Colley** [alishinski/lavaanPlot#47]
Hello there, I was wondering whether the newest version (0.8.1) will also be released on CRAN?

I think this will reach a lot of people then :)

Kind regards

**Comment by alishinski** [comment]
Thanks for your interest in the package! 

After a characteristically protracted delay, I have gotten version 0.8.1 onto CRAN: https://cran.r-project.org/web/packages/lavaanPlot/index.html
