### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by ajvandam** [alishinski/lavaanPlot#7]
First of all, lavaanPlot looks great and I hope it will work for me. 

When I enter this code:
lavaanPlot(model = m1_fit, labels = labels, node_options = list(shape = "box", fontname = "Helvetica"), edge_options = list(color = "grey"), coefs = TRUE, covs = TRUE)

I get an error:
Error in lavaanPlot(model = m1_fit, labels = labels, node_options = list(shape = "box",  : 
  unused arguments (coefs = TRUE, covs = TRUE)

Any ideas what I am doing wrong?

Greetings, 

Arjan

**Comment by alishinski** [comment]
I just tried your lavaanPlot call with an example from the vignette using the mtcars data and it worked correctly for me using lavaanPlot 0.5.1 downloaded from CRAN. Could you give me more info about your example? Did you download the package from CRAN or github?

**Comment by jorgesinval** [comment]
Where is the attachment?

**Comment by alishinski** [comment]
Yeah, I don't see that attachment either. One thing to make sure of is that your named list of labels uses the exact same names for the variables to identify them as in the fit model. Other than that, if you show me the output you're getting I can advise further.

**Comment by ajvandam** [comment]
Hi,

Sorry, that was the problem, I did use capitals in the script and not in
the call.... It works fine now!

Vriendelijke groet,

Fidare
Arjan van Dam

Heijermanslaan 27
1215 JL Hilversum
06-48865606
www.fidare.nl

2018-05-01 17:17 GMT+02:00 Alex Lishinski <notifications@github.com>:
